name: AWS Infrastructure Deployment for equiCast

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"
    workflow_dispatch:

jobs:
    lint:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        name: Lint and Validate Terraform
        permissions:
            contents: read
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.7.0
            
            - name: Terraform Format
              run: terraform fmt -recursive
              working-directory: equiCast

            - name: Terraform Init
              run: terraform init -backend=false -input=false
              working-directory: equiCast
            
            - name: Terraform Validate
              run: terraform validate -json
              working-directory: equiCast

    infracost:
        runs-on: ubuntu-latest
        name: Infracost Breakdown
        permissions:
            contents: read
            pull-requests: write
        needs: lint
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.7.0

            - name: Terraform Init
              run: terraform init -backend=false -input=false
              working-directory: equiCast

            - name: Setup Infracost
              uses: infracost/actions/setup@v3
              with:
                api-key: ${{ secrets.INFRACOST_API_KEY }}
            
            - name: Infracost Breakdown
              run: infracost breakdown --path equiCast --format table --project-name "equiCast" --show-skipped
    
    deploy:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        name: Deploy Infrastructure to AWS
        permissions:
            contents: read
            id-token: write
        needs: infracost
        env:
          AWS_REGION: eu-west-1
          TICKERS_BUCKET_NAME: equicast-tickers
          FXPAIRS_BUCKET_NAME: equicast-fxpairs
          INGESTION_BUCKET_NAME: equicast-ingestion
          CODEARTIFACT_DOMAIN_NAME: equicast-domain
          PYUTILS_CODEARTIFACT_NAME: equicast-pyutils-repo
          PYUTILS_VERSION_SSM_PARAMETER_NAME: /equicast/pyutils/version
          PYUTILS_VERSION_SSM_PARAMETER_VALUE: v0.0.0
          AWSUTILS_VERSION_SSM_PARAMETER_NAME: /equicast/awsutils/version
          AWSUTILS_VERSION_SSM_PARAMETER_VALUE: v0.0.0
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                aws-region: eu-west-1
                role-session-name: GitHubActionsSession

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.7.0

            - name: Terraform Init
              run: terraform init -input=false
              working-directory: equiCast

            - name: Terraform Plan
              run: |
                terraform plan -out=tfplan \
                  -var="region=$AWS_REGION" \
                  -var="tickers_bucket_name=$TICKERS_BUCKET_NAME" \
                  -var="fxpairs_bucket_name=$FXPAIRS_BUCKET_NAME" \
                  -var="ingestion_bucket_name=$INGESTION_BUCKET_NAME" \
                  -var="codeartifact_domain_name=$CODEARTIFACT_DOMAIN_NAME" \
                  -var="pyutils_codeartifact_name=$PYUTILS_CODEARTIFACT_NAME" \
                  -var="pyutils_version_ssm_parameter_name=$PYUTILS_VERSION_SSM_PARAMETER_NAME" \
                  -var="pyutils_version_ssm_parameter_value=$PYUTILS_VERSION_SSM_PARAMETER_VALUE" \
                  -var="awsutils_version_ssm_parameter_name=$AWSUTILS_VERSION_SSM_PARAMETER_NAME" \
                  -var="awsutils_version_ssm_parameter_value=$AWSUTILS_VERSION_SSM_PARAMETER_VALUE" \
                  -input=false
              working-directory: equiCast

            - name: Upload Terraform Plan
              uses: actions/upload-artifact@v4
              with:
                name: tfplan
                path: equiCast/tfplan
            
            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan
              working-directory: equiCast
